# Generated by Django 5.1.1 on 2024-09-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_author_student_content_student_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='photo',
            new_name='image',
        ),
    ]
