[phases.setup]
# Ensure Python is installed first
runtime = "python"
commands = [
  "python3 -m venv /opt/venv && . /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "npm install --prefix frontend_yearbook"
]

[phases.build]
commands = [
  "npm run build --prefix frontend_yearbook",
  "python manage.py collectstatic --noinput"
]

[phases.start]
commands = [
  "python manage.py migrate",
  "python manage.py runserver 0.0.0.0:$PORT"
]

[variables]
NODE_VERSION = "18.x"


