[phases.setup]
runtime = "python"
commands = [
  "apt-get update && apt-get install -y python3-pip python3-dev build-essential nodejs npm",
  "python3 -m venv /opt/venv && . /opt/venv/bin/activate",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r requirements.txt",
  "npm install --prefix frontend_yearbook"
]

[phases.build]
commands = [
  "npm run build --prefix frontend_yearbook",
  "/opt/venv/bin/python manage.py collectstatic --noinput"
]

[phases.start]
commands = [
  "/opt/venv/bin/python manage.py migrate",
  "/opt/venv/bin/python manage.py runserver 0.0.0.0:$PORT"
]

[variables]
NODE_VERSION = "18.x"



