services:
  - name: my-web-service
    type: web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn yearbook.wsgi
    plan: free
    deploy:
      hooks:
        afterDeploy:
          - python manage.py migrate
