# Generated by Django 4.2.10 on 2024-08-31 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_options'),
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Projects', to='students.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
